services:
  app:
    container_name: chrome_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ../:/app:delegated
    command: yarn dev
